name: Blue/Green Deployment

# run this code any time there is a push
# to the main branch
on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Execute dbt Cloud Job
        runs-on: ubuntu-latest
        steps:
            - name: Call dbt Cloud Job
              run: |
                curl --silent --write-out '%{http_code}' --fail --output /dev/null --request POST \
                     --url https://cloud.getdbt.com/api/v2/accounts/17878/jobs/138021/run/ \
                     --header 'Content-Type: application/json' \
                     --header 'Authorization: Token ${{ secrets.DBT_API_TOKEN }}' \
                     --data '{"cause":"Kicked off via GitHub Actions"}'