name: dbt Integration Test Run on PR

on:
  pull_request:
    branches:
      - '*'

jobs:
  run_dbt_on_pr:
    name: dbt Integration Test Run on PR
    runs-on: ubuntu-latest

    env:
      DBT_API_KEY:                ${{ secrets.DBT_API_TOKEN }}
      DBT_URL:                    https://cloud.getdbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
      DBT_JOB_CAUSE:              'Github Actions - Push to Main' # provide a descriptive job cause here for easy debugging down the road
      DBT_ACCOUNT_ID:             17878
      DBT_PROJECT_ID:             159017
      DBT_PR_JOB_ID:              169774
      TOOLKIT_AUTH_TOKEN:         ${{ secrets.toolkit_auth_token }}
      TOOLKIT_CLI_DOWNLOAD_URL:   ${{ secrets.toolkit_cli_download_url }}
      TOOLKIT_CLI_VERSION:        "0.10.0"
      SNOWFLAKE_USERNAME:         ${{ secrets.snowflake_username }}
      SNOWFLAKE_URL:              ${{ secrets.snowflake_url }}
      SNOWFLAKE_PASSWORD:         ${{ secrets.snowflake_password }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Trigger dbt job
      run: |
        python -u ./python/run_and_monitor_dbt_cloud_job.py

    - name: Move to the toolkit directory
      run: |
        cd ./toolkit

    - name: Download the toolkit-cli
      run: install-toolkit-cli
      shell: bash

    - name: Set up Java 
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: corretto
    
    - name: Profile test
      run: install/toolkit ds profile test

    - name: Profile prod
      run: install/toolkit ds profile prod

    - name: Diff Data Sources
      run: install/toolkit ds diff prod:profile:new test:profile:new
    
    - name: Generate Diff HTML
      run: install/toolkit ds show prod.test:diff:latest --format html -o ./profile.html

    - name: HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: 'profile.html'