name: Call Matillion on Production

on: 
  push:
    branches: 
      - 'main'

jobs:
  run_dbt_on_merge_to_master:
    name: Matillion Production Run on Push to Main
    runs-on: ubuntu-latest

    env:
      MATILLION_API_USER:     ${{ secrets.MATILLION_API_USER }} # error if no value, API username to connect to Matillion
      MATILLION_API_PASS:     ${{ secrets.MATILLION_API_PASS }} # error if no value, API password to connect to Matillion
      MATILLION_API_BASE:     'http://107.23.227.49' # error if no value, base url to connect to
      MATILLION_GROUP_NAME:   'phData%20Training'    # error if no value, group name
      MATILLION_PROJECT_NAME: 'Dakota_Kelley'        # error if no value, project name
      MATILLION_VERSION_NAME: 'default'              # error if no value, version name
      MATILLION_JOB_NAME:     'dbt_cloud'            # error if no value, job name
      MATILLION_ENV_NAME:     'Dakota_AWS'           # error if no value, env name

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Trigger dbt job
      run: |
        python -u ./python/run_and_monitor_matillion_orchestration.py